networks:
  traefik:
    driver: overlay
    ipam:
      config:
        - subnet: 10.43.0.0/22
    attachable: true

volumes:
  portainer-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.100,rw,nfsvers=4
      device: ":/mnt/big-chonk/srv-lab"
  acme-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.100,rw,nfsvers=4
      device: ":/mnt/big-chonk/srv-lab"

services:
  traefik:
    image: traefik:v3.3
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_API_KEY: ${CF_API_KEY}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/log/traefik:/var/log
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme-data:/acme.json
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.dok.kvd.studio`)
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: '8080'

  portainer:
    image: portainer/portainer-ce:2.24.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.http.routers.portainer.rule: Host(`portainer.dok.kvd.studio`)
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: '9000'
