name: core

networks:
  default:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: 10.42.0.0/22
          gateway: 10.42.0.1
    driver_opts:
      com.docker.network.bridge.name: traefik

volumes:
  portainer-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.100,rw,nfsvers=4
      device: ":/mnt/big-chonk/srv-lab"

services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_API_KEY: ${CF_API_KEY}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.lab2.kvd.studio`)
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 8080

  portainer:
    image: portainer/portainer-ce:2.24.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.lab2.kvd.studio`)
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000
